### ISSUE TITLE
Error line 17

### ISSUE THREAD

**Issue by MIKNOTAURO** [valdergallo/django_reset_migrations#6]
Hi Man, 
I'm trying to use your script and after run
python manage.py reset_migrations app1 app2 app3...
I got this
..../reset_migrations.py", line 17, in delete_line
    print_function('Deleting line in %s' % filename)
AttributeError: _Feature instance has no __call__ method

Do you have any idea what's going on?
***My apps has dependencies

thanks in advance :)

**Comment by valdergallo** [comment]
This is some problems in your python ...
