### ISSUE TITLE
Package is not compatible with python 3

### ISSUE THREAD

**Issue by dhrp** [valdergallo/django_reset_migrations#7]
It'd be nice if the package would be made compatible with python3, or a comment is made that it's not.

**Comment by artcry** [comment]
python 3 
----------
C:\Program Files>pip3 install django-reset-migrations
Collecting django-reset-migrations
  Using cached django-reset-migrations-0.1.0.tar.gz
Exception:
Traceback (most recent call last):
  File "c:\python\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xad in position 9: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\python\lib\site-packages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "c:\python\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\python\lib\site-packages\pip\req\req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "c:\python\lib\site-packages\pip\req\req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "c:\python\lib\site-packages\pip\req\req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "c:\python\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "c:\python\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xad in position 9: invalid start byte

**Comment by valdergallo** [comment]
Stranger I'll check this ...

**Comment by valdergallo** [comment]
I guys ... I don't know why that you are got error with python3k 

I tested here ... and is working with python3 

```
(.venv) valdergallo@mark42 ~/Sandbox/django-reset-migrations (master) $ pip install django-reset-migrations
Collecting django-reset-migrations
  Using cached https://files.pythonhosted.org/packages/41/37/62c2667ccca4516c2c220b258bf3144443228e3428bf9b121fecd14dee57/django_reset_migrations-0.3.1-py3-none-any.whl
Collecting django>=1.7
  Using cached https://files.pythonhosted.org/packages/55/d1/8ade70e65fa157e1903fe4078305ca53b6819ab212d9fbbe5755afc8ea2e/Django-3.0.2-py3-none-any.whl
Collecting pytz
  Using cached https://files.pythonhosted.org/packages/e7/f9/f0b53f88060247251bf481fa6ea62cd0d25bf1b11a87888e53ce5b7c8ad2/pytz-2019.3-py2.py3-none-any.whl
Collecting sqlparse>=0.2.2
  Using cached https://files.pythonhosted.org/packages/ef/53/900f7d2a54557c6a37886585a91336520e5539e3ae2423ff1102daf4f3a7/sqlparse-0.3.0-py2.py3-none-any.whl
Collecting asgiref~=3.2
  Using cached https://files.pythonhosted.org/packages/a5/cb/5a235b605a9753ebcb2730c75e610fb51c8cab3f01230080a8229fa36adb/asgiref-3.2.3-py2.py3-none-any.whl
Installing collected packages: pytz, sqlparse, asgiref, django, django-reset-migrations
Successfully installed asgiref-3.2.3 django-3.0.2 django-reset-migrations-0.3.1 pytz-2019.3 sqlparse-0.3.0
(.venv) valdergallo@mark42 ~/Sandbox/django-reset-migrations (master) $ pip --version
pip 19.3.1 from /Users/valdergallo/Sandbox/django-reset-migrations/.venv/lib/python3.7/site-packages/pip (python 3.7)
(.venv) valdergallo@mark42 ~/Sandbox/django-reset-migrations (master) $ python --version
Python 3.7.3
(.venv) valdergallo@mark42 ~/Sandbox/django-reset-migrations (master) $ pip freeze
asgiref==3.2.3
astroid==2.3.3
Django==3.0.2
django-reset-migrations==0.3.1
entrypoints==0.3
flake8==3.7.9
isort==4.3.21
lazy-object-proxy==1.4.3
mccabe==0.6.1
pycodestyle==2.5.0
pyflakes==2.1.1
pylint==2.4.4
pytz==2019.3
six==1.13.0
sqlparse==0.3.0
typed-ast==1.4.0
wrapt==1.11.2
```
